---

# playbook for Gogs
- hosts: all
  sudo: yes

  # roles:
  #   - nginx
    
  tasks:

    # Provision an instance 
    - local_action: script /home/mohan/Desktop/ansible-gogs/run.sh

    # populate ansible.cfg
    - local_action: script /home/mohan/Desktop/ansible-gogs/writehosts.sh
                
    - include: user.yml
    - include: dependencies.yml
    - include: nginx.yml
    - include: db.yml
    - include: app.yml


# ansible-playbook -i ansible.cfg -s -u ubuntu /home/mohan/Desktop/ansibleAssign/main.yml --private-key /home/mohan/.ssh/ans-gogs


        