---

# playbook for Gogs
- hosts: all
  sudo: yes

  # roles:
  #   - nginx
    
  tasks:
    - debug:
        msg: "main-gogs"

    - include: user.yml
    - include: nginx.yml
    - include: dependencies.yml
    - include: db.yml
    - include: app.yml


# ansible-playbook -i ansible.cfg -s -u ubuntu /home/mohan/Desktop/ansibleAssign/main.yml --private-key /home/mohan/.ssh/ans-gogs


        