---

# install nginx 
- name: Make sure to install nginx
  apt: pkg=nginx state=installed update_cache=true

- name: create ngnix dir
  file:
    path: /etc/nginx/sites-available/
    owner: git
    group: git
    mode: 0755
    state: directory
  sudo: yes
  sudo_user: git

- name: remove default file for nginx
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  sudo: yes
  sudo_user: git

- name: copy gogs to /etc/nginx
  template:
    src: /home/mohan/Desktop/ansible-gogs/playbooks/templates/gogs
    # dest: /home/git/gogs/custom/conf/app.ini  # Was included in the binary in the latest gogs
    dest: /etc/nginx/sites-available/gogs
    owner: "git"
    group: "git"
    mode: 0755
  sudo: yes
  sudo_user: git

# Activate the reverse proxy
- name: copy gogs.service file for systemd
  file:
    src: /etc/nginx/sites-available/gogs
    dest: /etc/nginx/sites-enabled/gogs
  become: true
  mode: 0755


# copy ngnix.service file for systemd
- name: copy nginx.service file for systemd
  template:
    src:  /home/mohan/Desktop/ansible-gogs/playbooks/templates/nginx.service
    dest: /etc/systemd/system/
    owner: "git"
    group: "git"
    mode: 0755
  sudo: yes
  sudo_user: git

- name: Reload nginx systemd service
  systemd: 
    state: started
    name: nginx 
    daemon_reload: yes
  sudo: yes

- name: Ensure nginx is running 
  service: 
    name: nginx 
    state: started 
    enabled: yes
  become: true 
 