---

- hosts: all

  vars:
    - MyMessage: "Welcome to Ansible Gogs!"
  
  tasks:
   - name: Nginx setup
     apt: pkg=nginx state=installed update_cache=true
   - name: html copy
     template: src=html.j2 dest=/usr/share/nginx/html/index.html
